apiVersion: v1
kind: Namespace
metadata:
  name: myapp

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: myapp
data:
  PGDB_HOST: postgre.postgre.svc.cluster.local
  PGDB_USER: postgres
  PGDB_NAME: postgres
  REDIS_HOST: cache-service.cache.svc.cluster.local



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: gauti12/myapp:v2  # replace with your Docker image name
          ports:
            - containerPort: 5000


---

apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myapp
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
